apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    velocity.tech.v1/dependsOn: bucket, queue, psql
    velocity.tech.v1/id: service
  name: service
  labels:
    app: web
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
        octopusexport: OctopusExport
    spec:
      containers:
        - name: service
          image: {{ .Values.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: BUCKET_NAME
              value: {{ .Values.bucket_name | toJson }}
            - name: DB_HOST
              value: {{ .Values.db_host | toJson }}
            - name: DB_PORT
              value: {{ .Values.db_port | toJson }}
            - name: DB_USER
              value: {{ .Values.db_user | toJson }}
            - name: DB_PASS
              value: {{ .Values.db_pass | toJson }}
            - name: QUEUE_NAME
              value: {{ .Values.queue_name | toJson }}
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.aws_access_key_id }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.aws_secret_access_key }}
            - name: AWS_SESSION_TOKEN
              value: {{ .Values.aws_session_token }}
