apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  annotations:
    velocity.tech.v1/dependsOn: mysql # Velocity dependencies declaration
type: Opaque
data:
  DB_USER: {{ .Values.db_user | b64enc }}
  DB_PASSWORD: {{ .Values.db_pass | b64enc }}