apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    velocity.tech.v1/dependsOn: pubsub-topic, pubsub-sub, mysql, bucket # Velocity dependencies declaration
    velocity.tech.v1/id: explorer # Velocity service identifier
  name: explorer
  labels:
    app: explorer
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: explorer
        octopusexport: OctopusExport
    spec:
      serviceAccountName: ksa
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      containers:
        - name: explorer
          image: {{ .Values.image }}
          ports:
            - containerPort: 80
          env:
            - name: PUBSUB_TOPIC
              value: {{ .Values.pubsub_topic_name | toJson  }}
            - name: PUBSUB_SUB
              value: {{ .Values.pubsub_sub_name | toJson  }}
            - name: GOOGLE_CLOUD_PROJECT
              value: {{ .Values.project_id }}
            - name: BUCKET_NAME
              value: {{ .Values.bucket_name | toJson  }}
            - name: DB_HOST
              value: {{ .Values.db_host | toJson  }}
