{{ if .Values.provision_resources }}
apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  annotations:
    cnrm.cloud.google.com/force-destroy: "true"
    cnrm.cloud.google.com/project-id: {{ .Values.project_id }}
    velocity.tech.v1/id: bucket # Velocity service identifier
  name: {{ .Values.bucket_name | toJson }}
spec:
  versioning:
    enabled: true
  uniformBucketLevelAccess: true
{{ end }}