{{ if .Values.provision_resources }}
apiVersion: sqs.velocity.tech/v1
kind: Queue
metadata:
  annotations:
    velocity.tech.v1/id: queue
  name: {{ .Values.queue_name | toJson }}
spec:
  queueName: {{ .Values.queue_name | toJson }}
{{ end }}