# API Reference is at https://aws-controllers-k8s.github.io/community/reference/dynamodb/v1alpha1/table/

apiVersion: dynamodb.services.k8s.aws/v1alpha1
kind: Table
metadata:
  annotations:
    velocity.tech.v1/exports-name: path="spec.tableName"
    velocity.tech.v1/id: dynamo
  name: "{velocity.v1.generate:cloudResourcePrefix}-my-table-var-service-id"
spec:
  tableName: "{velocity.v1.generate:cloudResourcePrefix}-my-table"
  attributeDefinitions:
    - attributeName: ID
      attributeType: S
  keySchema:
    - attributeName: ID
      keyType: HASH
  provisionedThroughput:
    readCapacityUnits: 5
    writeCapacityUnits: 5
  streamSpecification:
    streamEnabled: true
    streamViewType: NEW_AND_OLD_IMAGES
