---
apiVersion: sqs.velocity.tech/v1
kind: Queue
metadata:
  annotations:
    velocity.tech.v1/id: queue # Velocity service identifier
    velocity.tech.v1/exports-queue-name: path="metadata.name"
    velocity.tech.v1/exports-queue-url: path="spec.queueUrl"
    velocity.tech.v1/exports-queue-arn: path="spec.queueArn"
    velocity.tech.v1/dependsOn: queue
  name: "{velocity.v1.generate:cloudResourcePrefix(seed=queue)}-{velocity.v1.envName}-my-queue"
spec:
  queueName: "{velocity.v1:queue.exports.queue-name}"
  queueUrl:  "https://sqs.{velocity.v1.aws.region}.amazonaws.com/{velocity.v1.aws.accountID}/{velocity.v1:queue.exports.queue-name}"
  queueArn: "arn:aws:sqs:{velocity.v1.aws.region}:{velocity.v1.aws.accountID}:{velocity.v1:queue.exports.queue-name}"
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: service-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    velocity.tech.v1/id: service-a # Velocity service identifier
    velocity.tech.v1/dependsOn: queue

  name: service-a
  labels:
    app: service-a
spec:
  selector:
    matchLabels:
      app: service-a
  replicas: 1
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
        - name: service-a
          image: yeasy/simple-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
          - name: QUEUE_NAME
            value: "{velocity.v1:queue.exports.queue-name}"
          - name: QUEUE_URL
            value: "{velocity.v1:queue.exports.queue-url}"
---
