apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: service-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    velocity.tech.v1/id: service-a # Velocity service identifier
    velocity.tech.v1/dependsOn: service-b
  name: service-a
  labels:
    app: service-a
spec:
  selector:
    matchLabels:
      app: service-a
  replicas: 1
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
        - name: service-a
          image: yeasy/simple-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SERVICE_B_URL
              value: "http://{velocity.v1:service-b.exposures(port=http).host}:{velocity.v1:service-b.exposures(port=http).port}"
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: service-b
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    velocity.tech.v1/id: service-b # Velocity service identifier
    velocity.tech.v1/exposures-http-scheme: http

  name: service-b
  labels:
    app: service-b
spec:
  selector:
    matchLabels:
      app: service-b
  replicas: 1
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
        - name: service-b
          image: yeasy/simple-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
