apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: service-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    velocity.tech.v1/id: service-a # Velocity service identifier
  name: service-a
  labels:
    app: service-a
spec:
  selector:
    matchLabels:
      app: service-a
  replicas: 1
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
        - name: service-a
          image: yeasy/simple-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: rabbit-secrets
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: DB_USERNAME
                  optional: false # same as default; "mysecret" must exist
                  # and include a key named "username"
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-env
type: Opaque
data:
  DB_USERNAME: ZGItcGFzc3dvcmQte3ZlbG9jaXR5LnYxLmVudk5hbWV9 # base 64 encoding of "db-password-{velocity.v1.envName}"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbit-secrets
type: Opaque
data:
  RABBIT_USERNAME: cmFiYml0X3VzZXI= # base 64 encoding of "rabbit_user"
  RABBIT_PASSWORD: cmFiYml0LXBhc3N3b3JkLXt2ZWxvY2l0eS52MS5lbnZOYW1lfQ== # base 64 encoding of "rabbit-password-{velocity.v1.envName}"

---
