apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  annotations:
    velocity.tech.v1/dependsOn: psql # Velocity dependencies declaration
type: Opaque
stringData:
  DB_USER: "{velocity.v1:psql.exposures(port=tcp).user}"
  DB_PASS: "{velocity.v1:psql.exposures(port=tcp).password}"
