apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    velocity.tech.v1/dependsOn: bucket, queue, psql, dynamo
    velocity.tech.v1/id: service
  name: service
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: service
          image: gcr.io/velocity-playground/aws-service
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: AWS_REGION
              value: eu-central-1
            - name: BUCKET_NAME
              value: "{velocity.v1.generate:random([a-z]{1,64})}-{velocity.v1.envName}-my-bucket"
            - name: DB_HOST
              value: "{velocity.v1:psql.exposures(port=tcp).host}"
            - name: DB_PORT
              value: "{velocity.v1:psql.exposures(port=tcp).port}"
            - name: DB_USER
              value: "{velocity.v1:psql.exposures(port=tcp).user}"
            - name: DB_PASS
              value: "{velocity.v1:psql.exposures(port=tcp).password}"
            - name: QUEUE_NAME
              value: "{velocity.v1.envName}-my-queue"
            - name: DYNAMODB_TABLE_NAME
              value: "{velocity.v1.envName}-my-table"
            - name: AWS_ACCESS_KEY_ID
              value: "aws-access-key-id"
            - name: AWS_SECRET_ACCESS_KEY
              value: "aws-secret-access-key"
            - name: AWS_SESSION_TOKEN
              value: "aws-session-token"