apiVersion: sqs.velocity.tech/v1
kind: Queue
metadata:
  annotations:
    velocity.tech.v1/id: queue # Velocity service identifier
  name: "{velocity.v1.generate:cloudResourcePrefix(seed=queue)}-{velocity.v1.envName}-my-queue"
spec:
  queueName: "{velocity.v1.generate:cloudResourcePrefix(seed=queue)}-{velocity.v1.envName}-my-queue"