apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    velocity.tech.v1/id: mongo-var-service-id
    velocity.tech.v1/exposures-tcp-user: root
    velocity.tech.v1/exposures-tcp-password: path="spec.template.spec.containers.(name=mongodb).env.(name=MONGODB_ROOT_PASSWORD).value"
    velocity.tech.v1/exposures-tcp-scheme: "mongodb"
  name: mongodb-var-service-id
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongodb-var-service-id
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: mongodb-var-service-id
    spec:
      containers:
        - env:
            - name: MONGODB_ROOT_PASSWORD
              value: "password1234"
          image: bitnami/mongodb:4.4
          imagePullPolicy: IfNotPresent
          name: mongodb
          ports:
            - containerPort: 27017
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongodb-var-service-id
  name: mongodb-var-service-id
spec:
  ports:
    - name: tcp
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    name: mongodb-var-service-id
  type: ClusterIP
