apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  DB_USER: e3ZlbG9jaXR5LnYxOm15c3FsLmV4cG9zdXJlcyhwb3J0PW15c3FsKS51c2VyfQ== # base64 of "{velocity.v1:mysql.exposures(port=mysql).user}"
  DB_PASSWORD: e3ZlbG9jaXR5LnYxOm15c3FsLmV4cG9zdXJlcyhwb3J0PW15c3FsKS5wYXNzd29yZH0= # base64 of "{velocity.v1:mysql.exposures(port=mysql).password}"