apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  annotations:
    velocity.tech.v1/dependsOn: mysql # Velocity dependencies declaration
type: Opaque
stringData:
  DB_USER: "{velocity.v1:mysql.exposures(port=mysql).user}"
  DB_PASS: "{velocity.v1:mysql.exposures(port=mysql).password}"