apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  annotations:
    cnrm.cloud.google.com/force-destroy: "true"
    cnrm.cloud.google.com/project-id: velocity-playground
    velocity.tech.v1/id: bucket # Velocity service identifier
  name: "{velocity.v1.generate:random}-{velocity.v1.envName}-my-bucket"
spec:
  versioning:
    enabled: true
  uniformBucketLevelAccess: true
