---
# Source: mysql manual
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-10gb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql
  selector:
    name: mysql-database
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    velocity.tech.v1/id: mysql # Velocity service identifier
    velocity.tech.v1/exposures-mysql-user: path="spec.template.spec.containers.(name=mysql-database).env.(name=MYSQL_USER).value"
    velocity.tech.v1/exposures-mysql-password: path="spec.template.spec.containers.(name=mysql-database).env.(name=MYSQL_PASSWORD).value"
    velocity.tech.v1/exposures-mysql-scheme: mysql2
    velocity.tech.v1/exports-dbname: path="spec.template.spec.containers.(name=mysql-database).env.(name=MYSQL_DATABASE).value" # Velocity exported variable
  name: mysql-database
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: mysql-database
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: mysql-database
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: app_development
            - name: MYSQL_PASSWORD
              value: password123
            - name: MYSQL_ROOT_PASSWORD
              value: random_password
            - name: MYSQL_USER
              value: user123
          image: bitnami/mysql:5.7
          imagePullPolicy: IfNotPresent
          name: mysql-database
          ports:
            - containerPort: 3306
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /opt/bitnami/scripts/mysql/healthcheck.sh
            failureThreshold: 6
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: "1"
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 250Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /bitnami/mysql
              name: persistent-mysql-database-0
      dnsPolicy: ClusterFirst
      hostname: mysql-database
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      terminationGracePeriodSeconds: 30
      volumes:
        - name: persistent-mysql-database-0
          persistentVolumeClaim:
            claimName: pvc-10gb
---