apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    velocity.tech.v1/id: generic-service-var-service-id # Velocity service identifier
  name: generic-service-var-service-id
spec:
  replicas: 1
  selector:
    matchLabels:
      name: generic-service-var-service-id
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: generic-service-var-service-id
    spec:
      containers:
        - image: busybox:latest
          command:
            - sleep
            - infinity
          imagePullPolicy: IfNotPresent
          name: generic-service
      restartPolicy: Always