---
# Source: rabbit manual
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    velocity.tech.v1/id: rabbitmq
    velocity.tech.v1/exposures-tcp-user: path="spec.template.spec.containers.(name=rabbitmq).env.(name=RABBITMQ_DEFAULT_USER).value"
    velocity.tech.v1/exposures-tcp-password: path="spec.template.spec.containers.(name=rabbitmq).env.(name=RABBITMQ_DEFAULT_PASS).value"
    velocity.tech.v1/exposures-tcp-scheme: amqp
    velocity.tech.v1/exposures-tcp-management-isPublic: "true"
    velocity.tech.v1/exports-vhost: path="spec.template.spec.containers.(name=rabbitmq).env.(name=RABBITMQ_DEFAULT_VHOST).value"
  name: rabbitmq
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: rabbitmq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: rabbitmq
    spec:
      containers:
        - env:
            - name: RABBITMQ_DEFAULT_PASS
              value: password123
            - name: RABBITMQ_DEFAULT_USER
              value: username
            - name: RABBITMQ_DEFAULT_VHOST
              value: vhost123
          image: rabbitmq:3.8-management-alpine
          imagePullPolicy: IfNotPresent
          name: rabbitmq
          ports:
            - containerPort: 15672
              protocol: TCP
            - containerPort: 5672
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
    - name: tcp-management
      port: 15672
      protocol: TCP
      targetPort: 15672
    - name: tcp
      port: 5672
      protocol: TCP
      targetPort: 5672
  selector:
    name: rabbitmq
  type: ClusterIP
