apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  annotations:
    # This annotation will add this Secret to all newly created namespaces:
    kubed.appscode.com/sync: "microprod.velocity.tech/type=environment"
data:
  username: bXktYXBw
  password: Mzk1MjgkdmRnN0pi

